FROM php:8.4-cli

RUN apt-get update && apt-get install -y git zip libzip-dev && docker-php-ext-install zip pdo_mysql

WORKDIR /var/www/html

COPY . .

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install --prefer-dist --no-interaction

CMD ["./vendor/bin/phpunit"]
